name: SWF Derleyici
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Java Kur (Flex SDK için şart)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8' # Flex SDK en kararlı Java 8 ile çalışır

      - name: Adobe Flex SDK Kur ve Derle
        run: |
          wget https://archive.apache.org/dist/flex/4.16.1/binaries/apache-flex-sdk-4.16.1-binaries.tar.gz
          tar -xzf apache-flex-sdk-4.16.1-binaries.tar.gz
          
          # Derleyiciyi ve Java kütüphanelerini çalıştırılabilir yap
          chmod +x apache-flex-sdk-4.16.1-binaries/bin/mxmlc
          
          # AS3 Derleme Komutu
          ./apache-flex-sdk-4.16.1-binaries/bin/mxmlc oyun.as -static-link-runtime-shared-libraries=true -o sonuc.swf

      - name: Dosyayı Bana Ver
        uses: actions/upload-artifact@v4
        with:
          name: BenimOyunum
          path: sonuc.swf
